#!/usr/bin/env bash

set -euo pipefail

readonly PROFILES=(core mint wallet lightning tor)
readonly REPORT_DATE=$(date -u +%Y-%m-%d)
readonly REPORT_ROOT=$(mktemp -d)
readonly BODY_FILE="${REPORT_ROOT}/mutation-weekly-report.md"

total_actionable=0
incomplete_profiles=0

cleanup() {
    rm -rf "$REPORT_ROOT"
}
trap cleanup EXIT

count_status() {
    local results_file=$1
    local status=$2
    awk -F ': ' -v status="$status" \
        '$NF == status { count++ } END { print count + 0 }' "$results_file"
}

append_unavailable_profile() {
    local profile=$1
    local run_url=${2:-}

    if [[ -n "$run_url" ]]; then
        echo "| [${profile}](${run_url}) | unavailable | - | - | - | - | - |" \
            >> "$BODY_FILE"
    else
        echo "| ${profile} | unavailable | - | - | - | - | - |" >> "$BODY_FILE"
    fi
    incomplete_profiles=$((incomplete_profiles + 1))
}

collect_profile() {
    local profile=$1
    local workflow="mutation-${profile}.yml"
    local run_data

    if ! run_data=$(gh run list \
        --repo "$REPOSITORY" \
        --workflow "$workflow" \
        --event schedule \
        --limit 1 \
        --json databaseId,createdAt,url \
        --jq '.[0] // empty'); then
        append_unavailable_profile "$profile"
        return
    fi

    if [[ -z "$run_data" ]]; then
        append_unavailable_profile "$profile"
        return
    fi

    local run_id run_date run_url
    run_id=$(jq -r '.databaseId' <<< "$run_data")
    run_date=$(jq -r '.createdAt' <<< "$run_data")
    run_url=$(jq -r '.url' <<< "$run_data")

    if (( $(date -u -d "$run_date" +%s) < $(date -u -d '8 days ago' +%s) )); then
        echo "| [${profile}](${run_url}) | stale | - | - | - | - | - |" >> "$BODY_FILE"
        incomplete_profiles=$((incomplete_profiles + 1))
        return
    fi

    local report_dir="${REPORT_ROOT}/${profile}"
    local artifact="mutation-${profile}-${run_id}"
    mkdir -p "$report_dir"

    if ! gh run download "$run_id" \
        --repo "$REPOSITORY" \
        --name "$artifact" \
        --dir "$report_dir"; then
        append_unavailable_profile "$profile" "$run_url"
        return
    fi

    local results_file="${report_dir}/mutation-${profile}-results.txt"
    if [[ ! -f "$results_file" ]]; then
        append_unavailable_profile "$profile" "$run_url"
        return
    fi

    local killed survived no_tests timeout suspicious skipped
    killed=$(count_status "$results_file" killed)
    survived=$(count_status "$results_file" survived)
    no_tests=$(count_status "$results_file" "no tests")
    timeout=$(count_status "$results_file" timeout)
    suspicious=$(count_status "$results_file" suspicious)
    skipped=$(count_status "$results_file" skipped)
    total_actionable=$((total_actionable + survived + no_tests + timeout + suspicious))

    echo "| [${profile}](${run_url}) | ${killed} | ${survived} | ${no_tests} | ${timeout} | ${suspicious} | ${skipped} |" \
        >> "$BODY_FILE"
}

append_surviving_mutants() {
    local found_survivors=false

    {
        echo
        echo "### Surviving mutants"
        echo
        echo '```text'
    } >> "$BODY_FILE"

    for profile in "${PROFILES[@]}"; do
        local results_file="${REPORT_ROOT}/${profile}/mutation-${profile}-results.txt"
        [[ -f "$results_file" ]] || continue

        awk -F ': ' \
            '$NF == "survived" { print; if (++count == 10) exit }' \
            "$results_file" >> "$BODY_FILE"
        if grep -q ': survived$' "$results_file"; then
            found_survivors=true
        fi
    done

    if [[ "$found_survivors" == false ]]; then
        echo "No surviving mutants." >> "$BODY_FILE"
    fi
    echo '```' >> "$BODY_FILE"
}

append_action_items() {
    {
        echo
        echo "### Action items"
        echo
        echo "1. Review the surviving and untested mutations above."
        echo "2. Add tests for meaningful survivors or document equivalent mutations."
        echo "3. Follow each profile link for its complete results and log artifacts."
    } >> "$BODY_FILE"

    if (( incomplete_profiles > 0 )); then
        {
            echo
            echo "> [!WARNING]"
            echo "> ${incomplete_profiles} profile report(s) were missing or stale and need investigation."
        } >> "$BODY_FILE"
    fi

    {
        echo
        echo "_Generated by the weekly mutation-testing workflow._"
    } >> "$BODY_FILE"
}

ensure_labels() {
    gh label create mutation-testing \
        --repo "$REPOSITORY" \
        --color "7B2CBF" \
        --description "Mutation-testing results and improvements" \
        2>/dev/null || true
    gh label create weekly-report \
        --repo "$REPOSITORY" \
        --color "D4C5F9" \
        --description "Automated weekly reports" \
        2>/dev/null || true
}

if [[ -z "${REPOSITORY:-}" ]]; then
    echo "REPOSITORY must be set to the GitHub owner and repository." >&2
    exit 1
fi

{
    echo "## Mutation Testing Results"
    echo
    echo "Report date: ${REPORT_DATE}"
    echo
    echo "| Profile | Killed | Survived | No tests | Timeout | Suspicious | Skipped |"
    echo "|---|---:|---:|---:|---:|---:|---:|"
} > "$BODY_FILE"

for profile in "${PROFILES[@]}"; do
    collect_profile "$profile"
done

append_surviving_mutants
append_action_items

if (( total_actionable == 0 && incomplete_profiles == 0 )); then
    echo "All mutants were killed; no weekly issue is needed."
    exit 0
fi

ensure_labels
gh issue create \
    --repo "$REPOSITORY" \
    --title "🧬 Weekly Mutation Testing Report - ${REPORT_DATE}" \
    --label "mutation-testing,weekly-report" \
    --body-file "$BODY_FILE"
