# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import payment_processor_pb2 as payment__processor__pb2

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in payment_processor_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CdkPaymentProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSettings = channel.unary_unary(
            "/cdk_payment_processor.CdkPaymentProcessor/GetSettings",
            request_serializer=payment__processor__pb2.EmptyRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.SettingsResponse.FromString,
            _registered_method=True,
        )
        self.CreatePayment = channel.unary_unary(
            "/cdk_payment_processor.CdkPaymentProcessor/CreatePayment",
            request_serializer=payment__processor__pb2.CreatePaymentRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.CreatePaymentResponse.FromString,
            _registered_method=True,
        )
        self.GetPaymentQuote = channel.unary_unary(
            "/cdk_payment_processor.CdkPaymentProcessor/GetPaymentQuote",
            request_serializer=payment__processor__pb2.PaymentQuoteRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.PaymentQuoteResponse.FromString,
            _registered_method=True,
        )
        self.MakePayment = channel.unary_unary(
            "/cdk_payment_processor.CdkPaymentProcessor/MakePayment",
            request_serializer=payment__processor__pb2.MakePaymentRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.MakePaymentResponse.FromString,
            _registered_method=True,
        )
        self.CheckIncomingPayment = channel.unary_unary(
            "/cdk_payment_processor.CdkPaymentProcessor/CheckIncomingPayment",
            request_serializer=payment__processor__pb2.CheckIncomingPaymentRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.CheckIncomingPaymentResponse.FromString,
            _registered_method=True,
        )
        self.CheckOutgoingPayment = channel.unary_unary(
            "/cdk_payment_processor.CdkPaymentProcessor/CheckOutgoingPayment",
            request_serializer=payment__processor__pb2.CheckOutgoingPaymentRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.MakePaymentResponse.FromString,
            _registered_method=True,
        )
        self.WaitPaymentEvent = channel.unary_stream(
            "/cdk_payment_processor.CdkPaymentProcessor/WaitPaymentEvent",
            request_serializer=payment__processor__pb2.EmptyRequest.SerializeToString,
            response_deserializer=payment__processor__pb2.PaymentEventResponse.FromString,
            _registered_method=True,
        )


class CdkPaymentProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPaymentQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MakePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckIncomingPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckOutgoingPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WaitPaymentEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CdkPaymentProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSettings": grpc.unary_unary_rpc_method_handler(
            servicer.GetSettings,
            request_deserializer=payment__processor__pb2.EmptyRequest.FromString,
            response_serializer=payment__processor__pb2.SettingsResponse.SerializeToString,
        ),
        "CreatePayment": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePayment,
            request_deserializer=payment__processor__pb2.CreatePaymentRequest.FromString,
            response_serializer=payment__processor__pb2.CreatePaymentResponse.SerializeToString,
        ),
        "GetPaymentQuote": grpc.unary_unary_rpc_method_handler(
            servicer.GetPaymentQuote,
            request_deserializer=payment__processor__pb2.PaymentQuoteRequest.FromString,
            response_serializer=payment__processor__pb2.PaymentQuoteResponse.SerializeToString,
        ),
        "MakePayment": grpc.unary_unary_rpc_method_handler(
            servicer.MakePayment,
            request_deserializer=payment__processor__pb2.MakePaymentRequest.FromString,
            response_serializer=payment__processor__pb2.MakePaymentResponse.SerializeToString,
        ),
        "CheckIncomingPayment": grpc.unary_unary_rpc_method_handler(
            servicer.CheckIncomingPayment,
            request_deserializer=payment__processor__pb2.CheckIncomingPaymentRequest.FromString,
            response_serializer=payment__processor__pb2.CheckIncomingPaymentResponse.SerializeToString,
        ),
        "CheckOutgoingPayment": grpc.unary_unary_rpc_method_handler(
            servicer.CheckOutgoingPayment,
            request_deserializer=payment__processor__pb2.CheckOutgoingPaymentRequest.FromString,
            response_serializer=payment__processor__pb2.MakePaymentResponse.SerializeToString,
        ),
        "WaitPaymentEvent": grpc.unary_stream_rpc_method_handler(
            servicer.WaitPaymentEvent,
            request_deserializer=payment__processor__pb2.EmptyRequest.FromString,
            response_serializer=payment__processor__pb2.PaymentEventResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cdk_payment_processor.CdkPaymentProcessor", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "cdk_payment_processor.CdkPaymentProcessor", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CdkPaymentProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSettings(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/GetSettings",
            payment__processor__pb2.EmptyRequest.SerializeToString,
            payment__processor__pb2.SettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreatePayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/CreatePayment",
            payment__processor__pb2.CreatePaymentRequest.SerializeToString,
            payment__processor__pb2.CreatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPaymentQuote(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/GetPaymentQuote",
            payment__processor__pb2.PaymentQuoteRequest.SerializeToString,
            payment__processor__pb2.PaymentQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MakePayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/MakePayment",
            payment__processor__pb2.MakePaymentRequest.SerializeToString,
            payment__processor__pb2.MakePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckIncomingPayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/CheckIncomingPayment",
            payment__processor__pb2.CheckIncomingPaymentRequest.SerializeToString,
            payment__processor__pb2.CheckIncomingPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckOutgoingPayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/CheckOutgoingPayment",
            payment__processor__pb2.CheckOutgoingPaymentRequest.SerializeToString,
            payment__processor__pb2.MakePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WaitPaymentEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/cdk_payment_processor.CdkPaymentProcessor/WaitPaymentEvent",
            payment__processor__pb2.EmptyRequest.SerializeToString,
            payment__processor__pb2.PaymentEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
