"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PaymentIdentifierType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PaymentIdentifierTypeEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
        _PaymentIdentifierType.ValueType
    ],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PAYMENT_IDENTIFIER_TYPE_UNSPECIFIED: _PaymentIdentifierType.ValueType  # 0
    PAYMENT_IDENTIFIER_TYPE_PAYMENT_HASH: _PaymentIdentifierType.ValueType  # 1
    PAYMENT_IDENTIFIER_TYPE_OFFER_ID: _PaymentIdentifierType.ValueType  # 2
    PAYMENT_IDENTIFIER_TYPE_LABEL: _PaymentIdentifierType.ValueType  # 3
    PAYMENT_IDENTIFIER_TYPE_BOLT12_PAYMENT_HASH: _PaymentIdentifierType.ValueType  # 4
    PAYMENT_IDENTIFIER_TYPE_CUSTOM_ID: _PaymentIdentifierType.ValueType  # 5
    PAYMENT_IDENTIFIER_TYPE_PAYMENT_ID: _PaymentIdentifierType.ValueType  # 6
    PAYMENT_IDENTIFIER_TYPE_QUOTE_ID: _PaymentIdentifierType.ValueType  # 7

class PaymentIdentifierType(
    _PaymentIdentifierType, metaclass=_PaymentIdentifierTypeEnumTypeWrapper
): ...

PAYMENT_IDENTIFIER_TYPE_UNSPECIFIED: PaymentIdentifierType.ValueType  # 0
PAYMENT_IDENTIFIER_TYPE_PAYMENT_HASH: PaymentIdentifierType.ValueType  # 1
PAYMENT_IDENTIFIER_TYPE_OFFER_ID: PaymentIdentifierType.ValueType  # 2
PAYMENT_IDENTIFIER_TYPE_LABEL: PaymentIdentifierType.ValueType  # 3
PAYMENT_IDENTIFIER_TYPE_BOLT12_PAYMENT_HASH: PaymentIdentifierType.ValueType  # 4
PAYMENT_IDENTIFIER_TYPE_CUSTOM_ID: PaymentIdentifierType.ValueType  # 5
PAYMENT_IDENTIFIER_TYPE_PAYMENT_ID: PaymentIdentifierType.ValueType  # 6
PAYMENT_IDENTIFIER_TYPE_QUOTE_ID: PaymentIdentifierType.ValueType  # 7
global___PaymentIdentifierType = PaymentIdentifierType

class _OutgoingPaymentRequestType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OutgoingPaymentRequestTypeEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
        _OutgoingPaymentRequestType.ValueType
    ],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OUTGOING_PAYMENT_REQUEST_TYPE_UNSPECIFIED: (
        _OutgoingPaymentRequestType.ValueType
    )  # 0
    OUTGOING_PAYMENT_REQUEST_TYPE_BOLT11_INVOICE: (
        _OutgoingPaymentRequestType.ValueType
    )  # 1
    OUTGOING_PAYMENT_REQUEST_TYPE_BOLT12_OFFER: (
        _OutgoingPaymentRequestType.ValueType
    )  # 2
    OUTGOING_PAYMENT_REQUEST_TYPE_CUSTOM: _OutgoingPaymentRequestType.ValueType  # 3
    OUTGOING_PAYMENT_REQUEST_TYPE_ONCHAIN: _OutgoingPaymentRequestType.ValueType  # 4

class OutgoingPaymentRequestType(
    _OutgoingPaymentRequestType, metaclass=_OutgoingPaymentRequestTypeEnumTypeWrapper
): ...

OUTGOING_PAYMENT_REQUEST_TYPE_UNSPECIFIED: OutgoingPaymentRequestType.ValueType  # 0
OUTGOING_PAYMENT_REQUEST_TYPE_BOLT11_INVOICE: OutgoingPaymentRequestType.ValueType  # 1
OUTGOING_PAYMENT_REQUEST_TYPE_BOLT12_OFFER: OutgoingPaymentRequestType.ValueType  # 2
OUTGOING_PAYMENT_REQUEST_TYPE_CUSTOM: OutgoingPaymentRequestType.ValueType  # 3
OUTGOING_PAYMENT_REQUEST_TYPE_ONCHAIN: OutgoingPaymentRequestType.ValueType  # 4
global___OutgoingPaymentRequestType = OutgoingPaymentRequestType

class _QuoteState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _QuoteStateEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QuoteState.ValueType],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUOTE_STATE_UNSPECIFIED: _QuoteState.ValueType  # 0
    QUOTE_STATE_UNPAID: _QuoteState.ValueType  # 1
    QUOTE_STATE_PAID: _QuoteState.ValueType  # 2
    QUOTE_STATE_PENDING: _QuoteState.ValueType  # 3
    QUOTE_STATE_UNKNOWN: _QuoteState.ValueType  # 4
    QUOTE_STATE_FAILED: _QuoteState.ValueType  # 5
    QUOTE_STATE_ISSUED: _QuoteState.ValueType  # 6

class QuoteState(_QuoteState, metaclass=_QuoteStateEnumTypeWrapper): ...

QUOTE_STATE_UNSPECIFIED: QuoteState.ValueType  # 0
QUOTE_STATE_UNPAID: QuoteState.ValueType  # 1
QUOTE_STATE_PAID: QuoteState.ValueType  # 2
QUOTE_STATE_PENDING: QuoteState.ValueType  # 3
QUOTE_STATE_UNKNOWN: QuoteState.ValueType  # 4
QUOTE_STATE_FAILED: QuoteState.ValueType  # 5
QUOTE_STATE_ISSUED: QuoteState.ValueType  # 6
global___QuoteState = QuoteState

@typing.final
class EmptyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___EmptyRequest = EmptyRequest

@typing.final
class AmountMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    value: builtins.int
    unit: builtins.str
    def __init__(
        self,
        *,
        value: builtins.int = ...,
        unit: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["unit", b"unit", "value", b"value"]
    ) -> None: ...

global___AmountMessage = AmountMessage

@typing.final
class Bolt11Settings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MPP_FIELD_NUMBER: builtins.int
    AMOUNTLESS_FIELD_NUMBER: builtins.int
    INVOICE_DESCRIPTION_FIELD_NUMBER: builtins.int
    mpp: builtins.bool
    amountless: builtins.bool
    invoice_description: builtins.bool
    def __init__(
        self,
        *,
        mpp: builtins.bool = ...,
        amountless: builtins.bool = ...,
        invoice_description: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "amountless",
            b"amountless",
            "invoice_description",
            b"invoice_description",
            "mpp",
            b"mpp",
        ],
    ) -> None: ...

global___Bolt11Settings = Bolt11Settings

@typing.final
class Bolt12Settings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNTLESS_FIELD_NUMBER: builtins.int
    amountless: builtins.bool
    def __init__(
        self,
        *,
        amountless: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["amountless", b"amountless"]
    ) -> None: ...

global___Bolt12Settings = Bolt12Settings

@typing.final
class OnchainSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIRMATIONS_FIELD_NUMBER: builtins.int
    MIN_RECEIVE_AMOUNT_SAT_FIELD_NUMBER: builtins.int
    MIN_SEND_AMOUNT_SAT_FIELD_NUMBER: builtins.int
    confirmations: builtins.int
    min_receive_amount_sat: builtins.int
    min_send_amount_sat: builtins.int
    def __init__(
        self,
        *,
        confirmations: builtins.int = ...,
        min_receive_amount_sat: builtins.int = ...,
        min_send_amount_sat: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "confirmations",
            b"confirmations",
            "min_receive_amount_sat",
            b"min_receive_amount_sat",
            "min_send_amount_sat",
            b"min_send_amount_sat",
        ],
    ) -> None: ...

global___OnchainSettings = OnchainSettings

@typing.final
class SettingsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CustomEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    UNIT_FIELD_NUMBER: builtins.int
    BOLT11_FIELD_NUMBER: builtins.int
    BOLT12_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    ONCHAIN_FIELD_NUMBER: builtins.int
    unit: builtins.str
    @property
    def bolt11(self) -> global___Bolt11Settings: ...
    @property
    def bolt12(self) -> global___Bolt12Settings: ...
    @property
    def custom(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def onchain(self) -> global___OnchainSettings: ...
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        bolt11: global___Bolt11Settings | None = ...,
        bolt12: global___Bolt12Settings | None = ...,
        custom: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        onchain: global___OnchainSettings | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bolt11", b"bolt11", "bolt12", b"bolt12", "onchain", b"onchain"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bolt11",
            b"bolt11",
            "bolt12",
            b"bolt12",
            "custom",
            b"custom",
            "onchain",
            b"onchain",
            "unit",
            b"unit",
        ],
    ) -> None: ...

global___SettingsResponse = SettingsResponse

@typing.final
class Bolt11IncomingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    UNIX_EXPIRY_FIELD_NUMBER: builtins.int
    description: builtins.str
    unix_expiry: builtins.int
    @property
    def amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        description: builtins.str | None = ...,
        amount: global___AmountMessage | None = ...,
        unix_expiry: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_description",
            b"_description",
            "_unix_expiry",
            b"_unix_expiry",
            "amount",
            b"amount",
            "description",
            b"description",
            "unix_expiry",
            b"unix_expiry",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_description",
            b"_description",
            "_unix_expiry",
            b"_unix_expiry",
            "amount",
            b"amount",
            "description",
            b"description",
            "unix_expiry",
            b"unix_expiry",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_description", b"_description"]
    ) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_unix_expiry", b"_unix_expiry"]
    ) -> typing.Literal["unix_expiry"] | None: ...

global___Bolt11IncomingPaymentOptions = Bolt11IncomingPaymentOptions

@typing.final
class CustomIncomingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    UNIX_EXPIRY_FIELD_NUMBER: builtins.int
    EXTRA_JSON_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    PUBKEY_FIELD_NUMBER: builtins.int
    description: builtins.str
    unix_expiry: builtins.int
    extra_json: builtins.str
    quote_id: builtins.str
    pubkey: builtins.str
    @property
    def amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        description: builtins.str | None = ...,
        amount: global___AmountMessage | None = ...,
        unix_expiry: builtins.int | None = ...,
        extra_json: builtins.str | None = ...,
        quote_id: builtins.str = ...,
        pubkey: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_description",
            b"_description",
            "_extra_json",
            b"_extra_json",
            "_pubkey",
            b"_pubkey",
            "_unix_expiry",
            b"_unix_expiry",
            "amount",
            b"amount",
            "description",
            b"description",
            "extra_json",
            b"extra_json",
            "pubkey",
            b"pubkey",
            "unix_expiry",
            b"unix_expiry",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_description",
            b"_description",
            "_extra_json",
            b"_extra_json",
            "_pubkey",
            b"_pubkey",
            "_unix_expiry",
            b"_unix_expiry",
            "amount",
            b"amount",
            "description",
            b"description",
            "extra_json",
            b"extra_json",
            "pubkey",
            b"pubkey",
            "quote_id",
            b"quote_id",
            "unix_expiry",
            b"unix_expiry",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_amount", b"_amount"]
    ) -> typing.Literal["amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_description", b"_description"]
    ) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_extra_json", b"_extra_json"]
    ) -> typing.Literal["extra_json"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_pubkey", b"_pubkey"]
    ) -> typing.Literal["pubkey"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_unix_expiry", b"_unix_expiry"]
    ) -> typing.Literal["unix_expiry"] | None: ...

global___CustomIncomingPaymentOptions = CustomIncomingPaymentOptions

@typing.final
class Bolt12IncomingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    UNIX_EXPIRY_FIELD_NUMBER: builtins.int
    description: builtins.str
    unix_expiry: builtins.int
    @property
    def amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        description: builtins.str | None = ...,
        amount: global___AmountMessage | None = ...,
        unix_expiry: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_description",
            b"_description",
            "_unix_expiry",
            b"_unix_expiry",
            "amount",
            b"amount",
            "description",
            b"description",
            "unix_expiry",
            b"unix_expiry",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_description",
            b"_description",
            "_unix_expiry",
            b"_unix_expiry",
            "amount",
            b"amount",
            "description",
            b"description",
            "unix_expiry",
            b"unix_expiry",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_amount", b"_amount"]
    ) -> typing.Literal["amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_description", b"_description"]
    ) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_unix_expiry", b"_unix_expiry"]
    ) -> typing.Literal["unix_expiry"] | None: ...

global___Bolt12IncomingPaymentOptions = Bolt12IncomingPaymentOptions

@typing.final
class OnchainIncomingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["quote_id", b"quote_id"]
    ) -> None: ...

global___OnchainIncomingPaymentOptions = OnchainIncomingPaymentOptions

@typing.final
class IncomingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOLT11_FIELD_NUMBER: builtins.int
    BOLT12_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    ONCHAIN_FIELD_NUMBER: builtins.int
    @property
    def bolt11(self) -> global___Bolt11IncomingPaymentOptions: ...
    @property
    def bolt12(self) -> global___Bolt12IncomingPaymentOptions: ...
    @property
    def custom(self) -> global___CustomIncomingPaymentOptions: ...
    @property
    def onchain(self) -> global___OnchainIncomingPaymentOptions: ...
    def __init__(
        self,
        *,
        bolt11: global___Bolt11IncomingPaymentOptions | None = ...,
        bolt12: global___Bolt12IncomingPaymentOptions | None = ...,
        custom: global___CustomIncomingPaymentOptions | None = ...,
        onchain: global___OnchainIncomingPaymentOptions | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bolt11",
            b"bolt11",
            "bolt12",
            b"bolt12",
            "custom",
            b"custom",
            "onchain",
            b"onchain",
            "options",
            b"options",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bolt11",
            b"bolt11",
            "bolt12",
            b"bolt12",
            "custom",
            b"custom",
            "onchain",
            b"onchain",
            "options",
            b"options",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["options", b"options"]
    ) -> typing.Literal["bolt11", "bolt12", "custom", "onchain"] | None: ...

global___IncomingPaymentOptions = IncomingPaymentOptions

@typing.final
class CreatePaymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPTIONS_FIELD_NUMBER: builtins.int
    @property
    def options(self) -> global___IncomingPaymentOptions: ...
    def __init__(
        self,
        *,
        options: global___IncomingPaymentOptions | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["options", b"options"]
    ) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["options", b"options"]) -> None: ...

global___CreatePaymentRequest = CreatePaymentRequest

@typing.final
class PaymentIdentifier(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    type: global___PaymentIdentifierType.ValueType
    hash: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        type: global___PaymentIdentifierType.ValueType = ...,
        hash: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal["hash", b"hash", "id", b"id", "value", b"value"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "hash", b"hash", "id", b"id", "type", b"type", "value", b"value"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["value", b"value"]
    ) -> typing.Literal["hash", "id"] | None: ...

global___PaymentIdentifier = PaymentIdentifier

@typing.final
class CreatePaymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_IDENTIFIER_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    EXTRA_JSON_FIELD_NUMBER: builtins.int
    request: builtins.str
    expiry: builtins.int
    extra_json: builtins.str
    @property
    def request_identifier(self) -> global___PaymentIdentifier: ...
    def __init__(
        self,
        *,
        request_identifier: global___PaymentIdentifier | None = ...,
        request: builtins.str = ...,
        expiry: builtins.int | None = ...,
        extra_json: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_expiry",
            b"_expiry",
            "_extra_json",
            b"_extra_json",
            "expiry",
            b"expiry",
            "extra_json",
            b"extra_json",
            "request_identifier",
            b"request_identifier",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_expiry",
            b"_expiry",
            "_extra_json",
            b"_extra_json",
            "expiry",
            b"expiry",
            "extra_json",
            b"extra_json",
            "request",
            b"request",
            "request_identifier",
            b"request_identifier",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_expiry", b"_expiry"]
    ) -> typing.Literal["expiry"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_extra_json", b"_extra_json"]
    ) -> typing.Literal["extra_json"] | None: ...

global___CreatePaymentResponse = CreatePaymentResponse

@typing.final
class Mpp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    amount: builtins.int
    def __init__(
        self,
        *,
        amount: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount"]) -> None: ...

global___Mpp = Mpp

@typing.final
class Amountless(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_MSAT_FIELD_NUMBER: builtins.int
    amount_msat: builtins.int
    def __init__(
        self,
        *,
        amount_msat: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["amount_msat", b"amount_msat"]
    ) -> None: ...

global___Amountless = Amountless

@typing.final
class MeltOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MPP_FIELD_NUMBER: builtins.int
    AMOUNTLESS_FIELD_NUMBER: builtins.int
    @property
    def mpp(self) -> global___Mpp: ...
    @property
    def amountless(self) -> global___Amountless: ...
    def __init__(
        self,
        *,
        mpp: global___Mpp | None = ...,
        amountless: global___Amountless | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "amountless", b"amountless", "mpp", b"mpp", "options", b"options"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "amountless", b"amountless", "mpp", b"mpp", "options", b"options"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["options", b"options"]
    ) -> typing.Literal["mpp", "amountless"] | None: ...

global___MeltOptions = MeltOptions

@typing.final
class OnchainOutgoingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    MAX_FEE_AMOUNT_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    FEE_INDEX_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    address: builtins.str
    quote_id: builtins.str
    fee_index: builtins.int
    metadata: builtins.str
    @property
    def amount(self) -> global___AmountMessage: ...
    @property
    def max_fee_amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        amount: global___AmountMessage | None = ...,
        max_fee_amount: global___AmountMessage | None = ...,
        quote_id: builtins.str = ...,
        fee_index: builtins.int | None = ...,
        metadata: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_fee_index",
            b"_fee_index",
            "_max_fee_amount",
            b"_max_fee_amount",
            "_metadata",
            b"_metadata",
            "amount",
            b"amount",
            "fee_index",
            b"fee_index",
            "max_fee_amount",
            b"max_fee_amount",
            "metadata",
            b"metadata",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_fee_index",
            b"_fee_index",
            "_max_fee_amount",
            b"_max_fee_amount",
            "_metadata",
            b"_metadata",
            "address",
            b"address",
            "amount",
            b"amount",
            "fee_index",
            b"fee_index",
            "max_fee_amount",
            b"max_fee_amount",
            "metadata",
            b"metadata",
            "quote_id",
            b"quote_id",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_fee_index", b"_fee_index"]
    ) -> typing.Literal["fee_index"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_max_fee_amount", b"_max_fee_amount"]
    ) -> typing.Literal["max_fee_amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_metadata", b"_metadata"]
    ) -> typing.Literal["metadata"] | None: ...

global___OnchainOutgoingPaymentOptions = OnchainOutgoingPaymentOptions

@typing.final
class PaymentQuoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    REQUEST_TYPE_FIELD_NUMBER: builtins.int
    EXTRA_JSON_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    ONCHAIN_OPTIONS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    request: builtins.str
    unit: builtins.str
    request_type: global___OutgoingPaymentRequestType.ValueType
    extra_json: builtins.str
    quote_id: builtins.str
    @property
    def options(self) -> global___MeltOptions: ...
    @property
    def onchain_options(self) -> global___OnchainOutgoingPaymentOptions: ...
    @property
    def amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        request: builtins.str = ...,
        unit: builtins.str = ...,
        options: global___MeltOptions | None = ...,
        request_type: global___OutgoingPaymentRequestType.ValueType = ...,
        extra_json: builtins.str | None = ...,
        quote_id: builtins.str = ...,
        onchain_options: global___OnchainOutgoingPaymentOptions | None = ...,
        amount: global___AmountMessage | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_extra_json",
            b"_extra_json",
            "_onchain_options",
            b"_onchain_options",
            "_options",
            b"_options",
            "amount",
            b"amount",
            "extra_json",
            b"extra_json",
            "onchain_options",
            b"onchain_options",
            "options",
            b"options",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_extra_json",
            b"_extra_json",
            "_onchain_options",
            b"_onchain_options",
            "_options",
            b"_options",
            "amount",
            b"amount",
            "extra_json",
            b"extra_json",
            "onchain_options",
            b"onchain_options",
            "options",
            b"options",
            "quote_id",
            b"quote_id",
            "request",
            b"request",
            "request_type",
            b"request_type",
            "unit",
            b"unit",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_amount", b"_amount"]
    ) -> typing.Literal["amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_extra_json", b"_extra_json"]
    ) -> typing.Literal["extra_json"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_onchain_options", b"_onchain_options"]
    ) -> typing.Literal["onchain_options"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_options", b"_options"]
    ) -> typing.Literal["options"] | None: ...

global___PaymentQuoteRequest = PaymentQuoteRequest

@typing.final
class OnchainFeeOption(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEE_RESERVE_FIELD_NUMBER: builtins.int
    ESTIMATED_BLOCKS_FIELD_NUMBER: builtins.int
    FEE_INDEX_FIELD_NUMBER: builtins.int
    fee_reserve: builtins.int
    estimated_blocks: builtins.int
    fee_index: builtins.int
    def __init__(
        self,
        *,
        fee_reserve: builtins.int = ...,
        estimated_blocks: builtins.int = ...,
        fee_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "estimated_blocks",
            b"estimated_blocks",
            "fee_index",
            b"fee_index",
            "fee_reserve",
            b"fee_reserve",
        ],
    ) -> None: ...

global___OnchainFeeOption = OnchainFeeOption

@typing.final
class PaymentQuoteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_IDENTIFIER_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    FEE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    EXTRA_JSON_FIELD_NUMBER: builtins.int
    ESTIMATED_BLOCKS_FIELD_NUMBER: builtins.int
    FEE_OPTIONS_FIELD_NUMBER: builtins.int
    state: global___QuoteState.ValueType
    extra_json: builtins.str
    estimated_blocks: builtins.int
    @property
    def request_identifier(self) -> global___PaymentIdentifier: ...
    @property
    def amount(self) -> global___AmountMessage: ...
    @property
    def fee(self) -> global___AmountMessage: ...
    @property
    def fee_options(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___OnchainFeeOption
    ]: ...
    def __init__(
        self,
        *,
        request_identifier: global___PaymentIdentifier | None = ...,
        amount: global___AmountMessage | None = ...,
        fee: global___AmountMessage | None = ...,
        state: global___QuoteState.ValueType = ...,
        extra_json: builtins.str | None = ...,
        estimated_blocks: builtins.int | None = ...,
        fee_options: collections.abc.Iterable[global___OnchainFeeOption] | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_estimated_blocks",
            b"_estimated_blocks",
            "_extra_json",
            b"_extra_json",
            "amount",
            b"amount",
            "estimated_blocks",
            b"estimated_blocks",
            "extra_json",
            b"extra_json",
            "fee",
            b"fee",
            "request_identifier",
            b"request_identifier",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_estimated_blocks",
            b"_estimated_blocks",
            "_extra_json",
            b"_extra_json",
            "amount",
            b"amount",
            "estimated_blocks",
            b"estimated_blocks",
            "extra_json",
            b"extra_json",
            "fee",
            b"fee",
            "fee_options",
            b"fee_options",
            "request_identifier",
            b"request_identifier",
            "state",
            b"state",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_estimated_blocks", b"_estimated_blocks"]
    ) -> typing.Literal["estimated_blocks"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_extra_json", b"_extra_json"]
    ) -> typing.Literal["extra_json"] | None: ...

global___PaymentQuoteResponse = PaymentQuoteResponse

@typing.final
class Bolt11OutgoingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOLT11_FIELD_NUMBER: builtins.int
    MAX_FEE_AMOUNT_FIELD_NUMBER: builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    MELT_OPTIONS_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    bolt11: builtins.str
    timeout_secs: builtins.int
    quote_id: builtins.str
    @property
    def max_fee_amount(self) -> global___AmountMessage: ...
    @property
    def melt_options(self) -> global___MeltOptions: ...
    def __init__(
        self,
        *,
        bolt11: builtins.str = ...,
        max_fee_amount: global___AmountMessage | None = ...,
        timeout_secs: builtins.int | None = ...,
        melt_options: global___MeltOptions | None = ...,
        quote_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_max_fee_amount",
            b"_max_fee_amount",
            "_melt_options",
            b"_melt_options",
            "_timeout_secs",
            b"_timeout_secs",
            "max_fee_amount",
            b"max_fee_amount",
            "melt_options",
            b"melt_options",
            "timeout_secs",
            b"timeout_secs",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_max_fee_amount",
            b"_max_fee_amount",
            "_melt_options",
            b"_melt_options",
            "_timeout_secs",
            b"_timeout_secs",
            "bolt11",
            b"bolt11",
            "max_fee_amount",
            b"max_fee_amount",
            "melt_options",
            b"melt_options",
            "quote_id",
            b"quote_id",
            "timeout_secs",
            b"timeout_secs",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_max_fee_amount", b"_max_fee_amount"]
    ) -> typing.Literal["max_fee_amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_melt_options", b"_melt_options"]
    ) -> typing.Literal["melt_options"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_timeout_secs", b"_timeout_secs"]
    ) -> typing.Literal["timeout_secs"] | None: ...

global___Bolt11OutgoingPaymentOptions = Bolt11OutgoingPaymentOptions

@typing.final
class Bolt12OutgoingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OFFER_FIELD_NUMBER: builtins.int
    MAX_FEE_AMOUNT_FIELD_NUMBER: builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    MELT_OPTIONS_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    offer: builtins.str
    timeout_secs: builtins.int
    quote_id: builtins.str
    @property
    def max_fee_amount(self) -> global___AmountMessage: ...
    @property
    def melt_options(self) -> global___MeltOptions: ...
    def __init__(
        self,
        *,
        offer: builtins.str = ...,
        max_fee_amount: global___AmountMessage | None = ...,
        timeout_secs: builtins.int | None = ...,
        melt_options: global___MeltOptions | None = ...,
        quote_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_max_fee_amount",
            b"_max_fee_amount",
            "_melt_options",
            b"_melt_options",
            "_timeout_secs",
            b"_timeout_secs",
            "max_fee_amount",
            b"max_fee_amount",
            "melt_options",
            b"melt_options",
            "timeout_secs",
            b"timeout_secs",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_max_fee_amount",
            b"_max_fee_amount",
            "_melt_options",
            b"_melt_options",
            "_timeout_secs",
            b"_timeout_secs",
            "max_fee_amount",
            b"max_fee_amount",
            "melt_options",
            b"melt_options",
            "offer",
            b"offer",
            "quote_id",
            b"quote_id",
            "timeout_secs",
            b"timeout_secs",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_max_fee_amount", b"_max_fee_amount"]
    ) -> typing.Literal["max_fee_amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_melt_options", b"_melt_options"]
    ) -> typing.Literal["melt_options"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_timeout_secs", b"_timeout_secs"]
    ) -> typing.Literal["timeout_secs"] | None: ...

global___Bolt12OutgoingPaymentOptions = Bolt12OutgoingPaymentOptions

@typing.final
class CustomOutgoingPaymentOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OFFER_FIELD_NUMBER: builtins.int
    MAX_FEE_AMOUNT_FIELD_NUMBER: builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    MELT_OPTIONS_FIELD_NUMBER: builtins.int
    EXTRA_JSON_FIELD_NUMBER: builtins.int
    QUOTE_ID_FIELD_NUMBER: builtins.int
    offer: builtins.str
    timeout_secs: builtins.int
    extra_json: builtins.str
    quote_id: builtins.str
    @property
    def max_fee_amount(self) -> global___AmountMessage: ...
    @property
    def amount(self) -> global___AmountMessage: ...
    @property
    def melt_options(self) -> global___MeltOptions: ...
    def __init__(
        self,
        *,
        offer: builtins.str = ...,
        max_fee_amount: global___AmountMessage | None = ...,
        timeout_secs: builtins.int | None = ...,
        amount: global___AmountMessage | None = ...,
        melt_options: global___MeltOptions | None = ...,
        extra_json: builtins.str | None = ...,
        quote_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_extra_json",
            b"_extra_json",
            "_max_fee_amount",
            b"_max_fee_amount",
            "_melt_options",
            b"_melt_options",
            "_timeout_secs",
            b"_timeout_secs",
            "amount",
            b"amount",
            "extra_json",
            b"extra_json",
            "max_fee_amount",
            b"max_fee_amount",
            "melt_options",
            b"melt_options",
            "timeout_secs",
            b"timeout_secs",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_amount",
            b"_amount",
            "_extra_json",
            b"_extra_json",
            "_max_fee_amount",
            b"_max_fee_amount",
            "_melt_options",
            b"_melt_options",
            "_timeout_secs",
            b"_timeout_secs",
            "amount",
            b"amount",
            "extra_json",
            b"extra_json",
            "max_fee_amount",
            b"max_fee_amount",
            "melt_options",
            b"melt_options",
            "offer",
            b"offer",
            "quote_id",
            b"quote_id",
            "timeout_secs",
            b"timeout_secs",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_amount", b"_amount"]
    ) -> typing.Literal["amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_extra_json", b"_extra_json"]
    ) -> typing.Literal["extra_json"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_max_fee_amount", b"_max_fee_amount"]
    ) -> typing.Literal["max_fee_amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_melt_options", b"_melt_options"]
    ) -> typing.Literal["melt_options"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_timeout_secs", b"_timeout_secs"]
    ) -> typing.Literal["timeout_secs"] | None: ...

global___CustomOutgoingPaymentOptions = CustomOutgoingPaymentOptions

@typing.final
class OutgoingPaymentVariant(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOLT11_FIELD_NUMBER: builtins.int
    BOLT12_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    ONCHAIN_FIELD_NUMBER: builtins.int
    @property
    def bolt11(self) -> global___Bolt11OutgoingPaymentOptions: ...
    @property
    def bolt12(self) -> global___Bolt12OutgoingPaymentOptions: ...
    @property
    def custom(self) -> global___CustomOutgoingPaymentOptions: ...
    @property
    def onchain(self) -> global___OnchainOutgoingPaymentOptions: ...
    def __init__(
        self,
        *,
        bolt11: global___Bolt11OutgoingPaymentOptions | None = ...,
        bolt12: global___Bolt12OutgoingPaymentOptions | None = ...,
        custom: global___CustomOutgoingPaymentOptions | None = ...,
        onchain: global___OnchainOutgoingPaymentOptions | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bolt11",
            b"bolt11",
            "bolt12",
            b"bolt12",
            "custom",
            b"custom",
            "onchain",
            b"onchain",
            "options",
            b"options",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bolt11",
            b"bolt11",
            "bolt12",
            b"bolt12",
            "custom",
            b"custom",
            "onchain",
            b"onchain",
            "options",
            b"options",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["options", b"options"]
    ) -> typing.Literal["bolt11", "bolt12", "custom", "onchain"] | None: ...

global___OutgoingPaymentVariant = OutgoingPaymentVariant

@typing.final
class MakePaymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_OPTIONS_FIELD_NUMBER: builtins.int
    PARTIAL_AMOUNT_FIELD_NUMBER: builtins.int
    MAX_FEE_AMOUNT_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    unit: builtins.str
    @property
    def payment_options(self) -> global___OutgoingPaymentVariant: ...
    @property
    def partial_amount(self) -> global___AmountMessage: ...
    @property
    def max_fee_amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        payment_options: global___OutgoingPaymentVariant | None = ...,
        partial_amount: global___AmountMessage | None = ...,
        max_fee_amount: global___AmountMessage | None = ...,
        unit: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_max_fee_amount",
            b"_max_fee_amount",
            "_partial_amount",
            b"_partial_amount",
            "max_fee_amount",
            b"max_fee_amount",
            "partial_amount",
            b"partial_amount",
            "payment_options",
            b"payment_options",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_max_fee_amount",
            b"_max_fee_amount",
            "_partial_amount",
            b"_partial_amount",
            "max_fee_amount",
            b"max_fee_amount",
            "partial_amount",
            b"partial_amount",
            "payment_options",
            b"payment_options",
            "unit",
            b"unit",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_max_fee_amount", b"_max_fee_amount"]
    ) -> typing.Literal["max_fee_amount"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_partial_amount", b"_partial_amount"]
    ) -> typing.Literal["partial_amount"] | None: ...

global___MakePaymentRequest = MakePaymentRequest

@typing.final
class MakePaymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_IDENTIFIER_FIELD_NUMBER: builtins.int
    PAYMENT_PROOF_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    TOTAL_SPENT_FIELD_NUMBER: builtins.int
    EXTRA_JSON_FIELD_NUMBER: builtins.int
    payment_proof: builtins.str
    status: global___QuoteState.ValueType
    extra_json: builtins.str
    @property
    def payment_identifier(self) -> global___PaymentIdentifier: ...
    @property
    def total_spent(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        payment_identifier: global___PaymentIdentifier | None = ...,
        payment_proof: builtins.str | None = ...,
        status: global___QuoteState.ValueType = ...,
        total_spent: global___AmountMessage | None = ...,
        extra_json: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_extra_json",
            b"_extra_json",
            "_payment_proof",
            b"_payment_proof",
            "extra_json",
            b"extra_json",
            "payment_identifier",
            b"payment_identifier",
            "payment_proof",
            b"payment_proof",
            "total_spent",
            b"total_spent",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_extra_json",
            b"_extra_json",
            "_payment_proof",
            b"_payment_proof",
            "extra_json",
            b"extra_json",
            "payment_identifier",
            b"payment_identifier",
            "payment_proof",
            b"payment_proof",
            "status",
            b"status",
            "total_spent",
            b"total_spent",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_extra_json", b"_extra_json"]
    ) -> typing.Literal["extra_json"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_payment_proof", b"_payment_proof"]
    ) -> typing.Literal["payment_proof"] | None: ...

global___MakePaymentResponse = MakePaymentResponse

@typing.final
class CheckIncomingPaymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_IDENTIFIER_FIELD_NUMBER: builtins.int
    @property
    def request_identifier(self) -> global___PaymentIdentifier: ...
    def __init__(
        self,
        *,
        request_identifier: global___PaymentIdentifier | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["request_identifier", b"request_identifier"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["request_identifier", b"request_identifier"]
    ) -> None: ...

global___CheckIncomingPaymentRequest = CheckIncomingPaymentRequest

@typing.final
class WaitIncomingPaymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_IDENTIFIER_FIELD_NUMBER: builtins.int
    PAYMENT_AMOUNT_FIELD_NUMBER: builtins.int
    PAYMENT_ID_FIELD_NUMBER: builtins.int
    payment_id: builtins.str
    @property
    def payment_identifier(self) -> global___PaymentIdentifier: ...
    @property
    def payment_amount(self) -> global___AmountMessage: ...
    def __init__(
        self,
        *,
        payment_identifier: global___PaymentIdentifier | None = ...,
        payment_amount: global___AmountMessage | None = ...,
        payment_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "payment_amount",
            b"payment_amount",
            "payment_identifier",
            b"payment_identifier",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "payment_amount",
            b"payment_amount",
            "payment_id",
            b"payment_id",
            "payment_identifier",
            b"payment_identifier",
        ],
    ) -> None: ...

global___WaitIncomingPaymentResponse = WaitIncomingPaymentResponse

@typing.final
class CheckIncomingPaymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENTS_FIELD_NUMBER: builtins.int
    @property
    def payments(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___WaitIncomingPaymentResponse
    ]: ...
    def __init__(
        self,
        *,
        payments: collections.abc.Iterable[global___WaitIncomingPaymentResponse]
        | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["payments", b"payments"]
    ) -> None: ...

global___CheckIncomingPaymentResponse = CheckIncomingPaymentResponse

@typing.final
class CheckOutgoingPaymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_IDENTIFIER_FIELD_NUMBER: builtins.int
    @property
    def request_identifier(self) -> global___PaymentIdentifier: ...
    def __init__(
        self,
        *,
        request_identifier: global___PaymentIdentifier | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["request_identifier", b"request_identifier"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["request_identifier", b"request_identifier"]
    ) -> None: ...

global___CheckOutgoingPaymentRequest = CheckOutgoingPaymentRequest

@typing.final
class PaymentSuccessfulResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    @property
    def details(self) -> global___MakePaymentResponse: ...
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
        details: global___MakePaymentResponse | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["details", b"details"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["details", b"details", "quote_id", b"quote_id"]
    ) -> None: ...

global___PaymentSuccessfulResponse = PaymentSuccessfulResponse

@typing.final
class PaymentFailedResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    reason: builtins.str
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["quote_id", b"quote_id", "reason", b"reason"]
    ) -> None: ...

global___PaymentFailedResponse = PaymentFailedResponse

@typing.final
class PaymentEventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_RECEIVED_FIELD_NUMBER: builtins.int
    PAYMENT_SUCCESSFUL_FIELD_NUMBER: builtins.int
    PAYMENT_FAILED_FIELD_NUMBER: builtins.int
    @property
    def payment_received(self) -> global___WaitIncomingPaymentResponse: ...
    @property
    def payment_successful(self) -> global___PaymentSuccessfulResponse: ...
    @property
    def payment_failed(self) -> global___PaymentFailedResponse: ...
    def __init__(
        self,
        *,
        payment_received: global___WaitIncomingPaymentResponse | None = ...,
        payment_successful: global___PaymentSuccessfulResponse | None = ...,
        payment_failed: global___PaymentFailedResponse | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "event",
            b"event",
            "payment_failed",
            b"payment_failed",
            "payment_received",
            b"payment_received",
            "payment_successful",
            b"payment_successful",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "event",
            b"event",
            "payment_failed",
            b"payment_failed",
            "payment_received",
            b"payment_received",
            "payment_successful",
            b"payment_successful",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["event", b"event"]
    ) -> (
        typing.Literal["payment_received", "payment_successful", "payment_failed"]
        | None
    ): ...

global___PaymentEventResponse = PaymentEventResponse
