"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import typing

import grpc
import grpc.aio
import payment_processor_pb2

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(
    collections.abc.AsyncIterator[_T],
    collections.abc.Iterator[_T],
    metaclass=abc.ABCMeta,
): ...
class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class CdkPaymentProcessorStub:
    def __init__(
        self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]
    ) -> None: ...
    GetSettings: grpc.UnaryUnaryMultiCallable[
        payment_processor_pb2.EmptyRequest,
        payment_processor_pb2.SettingsResponse,
    ]

    CreatePayment: grpc.UnaryUnaryMultiCallable[
        payment_processor_pb2.CreatePaymentRequest,
        payment_processor_pb2.CreatePaymentResponse,
    ]

    GetPaymentQuote: grpc.UnaryUnaryMultiCallable[
        payment_processor_pb2.PaymentQuoteRequest,
        payment_processor_pb2.PaymentQuoteResponse,
    ]

    MakePayment: grpc.UnaryUnaryMultiCallable[
        payment_processor_pb2.MakePaymentRequest,
        payment_processor_pb2.MakePaymentResponse,
    ]

    CheckIncomingPayment: grpc.UnaryUnaryMultiCallable[
        payment_processor_pb2.CheckIncomingPaymentRequest,
        payment_processor_pb2.CheckIncomingPaymentResponse,
    ]

    CheckOutgoingPayment: grpc.UnaryUnaryMultiCallable[
        payment_processor_pb2.CheckOutgoingPaymentRequest,
        payment_processor_pb2.MakePaymentResponse,
    ]

    WaitPaymentEvent: grpc.UnaryStreamMultiCallable[
        payment_processor_pb2.EmptyRequest,
        payment_processor_pb2.PaymentEventResponse,
    ]

class CdkPaymentProcessorAsyncStub:
    GetSettings: grpc.aio.UnaryUnaryMultiCallable[
        payment_processor_pb2.EmptyRequest,
        payment_processor_pb2.SettingsResponse,
    ]

    CreatePayment: grpc.aio.UnaryUnaryMultiCallable[
        payment_processor_pb2.CreatePaymentRequest,
        payment_processor_pb2.CreatePaymentResponse,
    ]

    GetPaymentQuote: grpc.aio.UnaryUnaryMultiCallable[
        payment_processor_pb2.PaymentQuoteRequest,
        payment_processor_pb2.PaymentQuoteResponse,
    ]

    MakePayment: grpc.aio.UnaryUnaryMultiCallable[
        payment_processor_pb2.MakePaymentRequest,
        payment_processor_pb2.MakePaymentResponse,
    ]

    CheckIncomingPayment: grpc.aio.UnaryUnaryMultiCallable[
        payment_processor_pb2.CheckIncomingPaymentRequest,
        payment_processor_pb2.CheckIncomingPaymentResponse,
    ]

    CheckOutgoingPayment: grpc.aio.UnaryUnaryMultiCallable[
        payment_processor_pb2.CheckOutgoingPaymentRequest,
        payment_processor_pb2.MakePaymentResponse,
    ]

    WaitPaymentEvent: grpc.aio.UnaryStreamMultiCallable[
        payment_processor_pb2.EmptyRequest,
        payment_processor_pb2.PaymentEventResponse,
    ]

class CdkPaymentProcessorServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetSettings(
        self,
        request: payment_processor_pb2.EmptyRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        payment_processor_pb2.SettingsResponse,
        collections.abc.Awaitable[payment_processor_pb2.SettingsResponse],
    ]: ...
    @abc.abstractmethod
    def CreatePayment(
        self,
        request: payment_processor_pb2.CreatePaymentRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        payment_processor_pb2.CreatePaymentResponse,
        collections.abc.Awaitable[payment_processor_pb2.CreatePaymentResponse],
    ]: ...
    @abc.abstractmethod
    def GetPaymentQuote(
        self,
        request: payment_processor_pb2.PaymentQuoteRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        payment_processor_pb2.PaymentQuoteResponse,
        collections.abc.Awaitable[payment_processor_pb2.PaymentQuoteResponse],
    ]: ...
    @abc.abstractmethod
    def MakePayment(
        self,
        request: payment_processor_pb2.MakePaymentRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        payment_processor_pb2.MakePaymentResponse,
        collections.abc.Awaitable[payment_processor_pb2.MakePaymentResponse],
    ]: ...
    @abc.abstractmethod
    def CheckIncomingPayment(
        self,
        request: payment_processor_pb2.CheckIncomingPaymentRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        payment_processor_pb2.CheckIncomingPaymentResponse,
        collections.abc.Awaitable[payment_processor_pb2.CheckIncomingPaymentResponse],
    ]: ...
    @abc.abstractmethod
    def CheckOutgoingPayment(
        self,
        request: payment_processor_pb2.CheckOutgoingPaymentRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        payment_processor_pb2.MakePaymentResponse,
        collections.abc.Awaitable[payment_processor_pb2.MakePaymentResponse],
    ]: ...
    @abc.abstractmethod
    def WaitPaymentEvent(
        self,
        request: payment_processor_pb2.EmptyRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        collections.abc.Iterator[payment_processor_pb2.PaymentEventResponse],
        collections.abc.AsyncIterator[payment_processor_pb2.PaymentEventResponse],
    ]: ...

def add_CdkPaymentProcessorServicer_to_server(
    servicer: CdkPaymentProcessorServicer,
    server: typing.Union[grpc.Server, grpc.aio.Server],
) -> None: ...
