"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetInfoRequest = GetInfoRequest

@typing.final
class MintInfoContact(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    method: builtins.str
    info: builtins.str
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "method", b"method"]) -> None: ...

global___MintInfoContact = MintInfoContact

@typing.final
class GetInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PUBKEY_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DESCRIPTION_LONG_FIELD_NUMBER: builtins.int
    CONTACT_FIELD_NUMBER: builtins.int
    MOTD_FIELD_NUMBER: builtins.int
    ICON_URL_FIELD_NUMBER: builtins.int
    URLS_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    TOS_URL_FIELD_NUMBER: builtins.int
    name: builtins.str
    pubkey: builtins.str
    version: builtins.str
    description: builtins.str
    description_long: builtins.str
    motd: builtins.str
    icon_url: builtins.str
    time: builtins.int
    tos_url: builtins.str
    @property
    def contact(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MintInfoContact]: ...
    @property
    def urls(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        pubkey: builtins.str | None = ...,
        version: builtins.str | None = ...,
        description: builtins.str | None = ...,
        description_long: builtins.str | None = ...,
        contact: collections.abc.Iterable[global___MintInfoContact] | None = ...,
        motd: builtins.str | None = ...,
        icon_url: builtins.str | None = ...,
        urls: collections.abc.Iterable[builtins.str] | None = ...,
        time: builtins.int | None = ...,
        tos_url: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_description_long", b"_description_long", "_icon_url", b"_icon_url", "_motd", b"_motd", "_name", b"_name", "_pubkey", b"_pubkey", "_time", b"_time", "_tos_url", b"_tos_url", "_version", b"_version", "description", b"description", "description_long", b"description_long", "icon_url", b"icon_url", "motd", b"motd", "name", b"name", "pubkey", b"pubkey", "time", b"time", "tos_url", b"tos_url", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_description_long", b"_description_long", "_icon_url", b"_icon_url", "_motd", b"_motd", "_name", b"_name", "_pubkey", b"_pubkey", "_time", b"_time", "_tos_url", b"_tos_url", "_version", b"_version", "contact", b"contact", "description", b"description", "description_long", b"description_long", "icon_url", b"icon_url", "motd", b"motd", "name", b"name", "pubkey", b"pubkey", "time", b"time", "tos_url", b"tos_url", "urls", b"urls", "version", b"version"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description_long", b"_description_long"]) -> typing.Literal["description_long"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_icon_url", b"_icon_url"]) -> typing.Literal["icon_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_motd", b"_motd"]) -> typing.Literal["motd"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pubkey", b"_pubkey"]) -> typing.Literal["pubkey"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_time", b"_time"]) -> typing.Literal["time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tos_url", b"_tos_url"]) -> typing.Literal["tos_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_version", b"_version"]) -> typing.Literal["version"] | None: ...

global___GetInfoResponse = GetInfoResponse

@typing.final
class UpdateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateResponse = UpdateResponse

@typing.final
class UpdateMotdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOTD_FIELD_NUMBER: builtins.int
    motd: builtins.str
    def __init__(
        self,
        *,
        motd: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["motd", b"motd"]) -> None: ...

global___UpdateMotdRequest = UpdateMotdRequest

@typing.final
class UpdateDescriptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    description: builtins.str
    def __init__(
        self,
        *,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description"]) -> None: ...

global___UpdateDescriptionRequest = UpdateDescriptionRequest

@typing.final
class UpdateIconUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ICON_URL_FIELD_NUMBER: builtins.int
    icon_url: builtins.str
    def __init__(
        self,
        *,
        icon_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["icon_url", b"icon_url"]) -> None: ...

global___UpdateIconUrlRequest = UpdateIconUrlRequest

@typing.final
class UpdateNameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___UpdateNameRequest = UpdateNameRequest

@typing.final
class UpdateUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["url", b"url"]) -> None: ...

global___UpdateUrlRequest = UpdateUrlRequest

@typing.final
class UpdateContactRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    method: builtins.str
    info: builtins.str
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "method", b"method"]) -> None: ...

global___UpdateContactRequest = UpdateContactRequest

@typing.final
class UpdateNut04Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    unit: builtins.str
    method: builtins.str
    disabled: builtins.bool
    min: builtins.int
    max: builtins.int
    description: builtins.bool
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        method: builtins.str = ...,
        disabled: builtins.bool | None = ...,
        min: builtins.int | None = ...,
        max: builtins.int | None = ...,
        description: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "description", b"description", "disabled", b"disabled", "max", b"max", "min", b"min"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "description", b"description", "disabled", b"disabled", "max", b"max", "method", b"method", "min", b"min", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_disabled", b"_disabled"]) -> typing.Literal["disabled"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max", b"_max"]) -> typing.Literal["max"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_min", b"_min"]) -> typing.Literal["min"] | None: ...

global___UpdateNut04Request = UpdateNut04Request

@typing.final
class UpdateNut05Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    unit: builtins.str
    method: builtins.str
    disabled: builtins.bool
    min: builtins.int
    max: builtins.int
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        method: builtins.str = ...,
        disabled: builtins.bool | None = ...,
        min: builtins.int | None = ...,
        max: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "disabled", b"disabled", "max", b"max", "min", b"min"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "disabled", b"disabled", "max", b"max", "method", b"method", "min", b"min", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_disabled", b"_disabled"]) -> typing.Literal["disabled"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max", b"_max"]) -> typing.Literal["max"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_min", b"_min"]) -> typing.Literal["min"] | None: ...

global___UpdateNut05Request = UpdateNut05Request

@typing.final
class UpdateQuoteTtlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TTL_FIELD_NUMBER: builtins.int
    ttl: builtins.int
    def __init__(
        self,
        *,
        ttl: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_ttl", b"_ttl", "ttl", b"ttl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_ttl", b"_ttl", "ttl", b"ttl"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_ttl", b"_ttl"]) -> typing.Literal["ttl"] | None: ...

global___UpdateQuoteTtlRequest = UpdateQuoteTtlRequest

@typing.final
class Nut04Quote(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    CHECKING_ID_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    CREATED_TIME_FIELD_NUMBER: builtins.int
    PAID_TIME_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    PUBKEY_FIELD_NUMBER: builtins.int
    quote: builtins.str
    method: builtins.str
    request: builtins.str
    checking_id: builtins.str
    unit: builtins.str
    amount: builtins.int
    state: builtins.str
    created_time: builtins.int
    paid_time: builtins.int
    expiry: builtins.int
    pubkey: builtins.str
    def __init__(
        self,
        *,
        quote: builtins.str = ...,
        method: builtins.str = ...,
        request: builtins.str = ...,
        checking_id: builtins.str = ...,
        unit: builtins.str = ...,
        amount: builtins.int = ...,
        state: builtins.str | None = ...,
        created_time: builtins.int | None = ...,
        paid_time: builtins.int | None = ...,
        expiry: builtins.int | None = ...,
        pubkey: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_created_time", b"_created_time", "_expiry", b"_expiry", "_paid_time", b"_paid_time", "_pubkey", b"_pubkey", "_state", b"_state", "created_time", b"created_time", "expiry", b"expiry", "paid_time", b"paid_time", "pubkey", b"pubkey", "state", b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_created_time", b"_created_time", "_expiry", b"_expiry", "_paid_time", b"_paid_time", "_pubkey", b"_pubkey", "_state", b"_state", "amount", b"amount", "checking_id", b"checking_id", "created_time", b"created_time", "expiry", b"expiry", "method", b"method", "paid_time", b"paid_time", "pubkey", b"pubkey", "quote", b"quote", "request", b"request", "state", b"state", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_created_time", b"_created_time"]) -> typing.Literal["created_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_expiry", b"_expiry"]) -> typing.Literal["expiry"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_paid_time", b"_paid_time"]) -> typing.Literal["paid_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pubkey", b"_pubkey"]) -> typing.Literal["pubkey"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_state", b"_state"]) -> typing.Literal["state"] | None: ...

global___Nut04Quote = Nut04Quote

@typing.final
class BlindedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    B__FIELD_NUMBER: builtins.int
    WITNESS_FIELD_NUMBER: builtins.int
    amount: builtins.int
    id: builtins.str
    B_: builtins.str
    witness: builtins.str
    def __init__(
        self,
        *,
        amount: builtins.int = ...,
        id: builtins.str = ...,
        B_: builtins.str = ...,
        witness: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_witness", b"_witness", "witness", b"witness"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["B_", b"B_", "_witness", b"_witness", "amount", b"amount", "id", b"id", "witness", b"witness"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_witness", b"_witness"]) -> typing.Literal["witness"] | None: ...

global___BlindedMessage = BlindedMessage

@typing.final
class DLEQ(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    E_FIELD_NUMBER: builtins.int
    S_FIELD_NUMBER: builtins.int
    e: builtins.str
    s: builtins.str
    def __init__(
        self,
        *,
        e: builtins.str = ...,
        s: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["e", b"e", "s", b"s"]) -> None: ...

global___DLEQ = DLEQ

@typing.final
class BlindedSignature(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    C__FIELD_NUMBER: builtins.int
    DLEQ_FIELD_NUMBER: builtins.int
    id: builtins.str
    amount: builtins.int
    C_: builtins.str
    @property
    def dleq(self) -> global___DLEQ: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        amount: builtins.int = ...,
        C_: builtins.str = ...,
        dleq: global___DLEQ | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dleq", b"_dleq", "dleq", b"dleq"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["C_", b"C_", "_dleq", b"_dleq", "amount", b"amount", "dleq", b"dleq", "id", b"id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_dleq", b"_dleq"]) -> typing.Literal["dleq"] | None: ...

global___BlindedSignature = BlindedSignature

@typing.final
class Nut05Quote(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    CHECKING_ID_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    FEE_RESERVE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    CREATED_TIME_FIELD_NUMBER: builtins.int
    PAID_TIME_FIELD_NUMBER: builtins.int
    FEE_PAID_FIELD_NUMBER: builtins.int
    PAYMENT_PREIMAGE_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    CHANGE_FIELD_NUMBER: builtins.int
    quote: builtins.str
    method: builtins.str
    request: builtins.str
    checking_id: builtins.str
    unit: builtins.str
    amount: builtins.int
    fee_reserve: builtins.int
    state: builtins.str
    created_time: builtins.int
    paid_time: builtins.int
    fee_paid: builtins.int
    payment_preimage: builtins.str
    expiry: builtins.int
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlindedMessage]: ...
    @property
    def change(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlindedSignature]: ...
    def __init__(
        self,
        *,
        quote: builtins.str = ...,
        method: builtins.str = ...,
        request: builtins.str = ...,
        checking_id: builtins.str = ...,
        unit: builtins.str = ...,
        amount: builtins.int = ...,
        fee_reserve: builtins.int = ...,
        state: builtins.str = ...,
        created_time: builtins.int | None = ...,
        paid_time: builtins.int | None = ...,
        fee_paid: builtins.int = ...,
        payment_preimage: builtins.str | None = ...,
        expiry: builtins.int | None = ...,
        outputs: collections.abc.Iterable[global___BlindedMessage] | None = ...,
        change: collections.abc.Iterable[global___BlindedSignature] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_created_time", b"_created_time", "_expiry", b"_expiry", "_paid_time", b"_paid_time", "_payment_preimage", b"_payment_preimage", "created_time", b"created_time", "expiry", b"expiry", "paid_time", b"paid_time", "payment_preimage", b"payment_preimage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_created_time", b"_created_time", "_expiry", b"_expiry", "_paid_time", b"_paid_time", "_payment_preimage", b"_payment_preimage", "amount", b"amount", "change", b"change", "checking_id", b"checking_id", "created_time", b"created_time", "expiry", b"expiry", "fee_paid", b"fee_paid", "fee_reserve", b"fee_reserve", "method", b"method", "outputs", b"outputs", "paid_time", b"paid_time", "payment_preimage", b"payment_preimage", "quote", b"quote", "request", b"request", "state", b"state", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_created_time", b"_created_time"]) -> typing.Literal["created_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_expiry", b"_expiry"]) -> typing.Literal["expiry"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_paid_time", b"_paid_time"]) -> typing.Literal["paid_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_payment_preimage", b"_payment_preimage"]) -> typing.Literal["payment_preimage"] | None: ...

global___Nut05Quote = Nut05Quote

@typing.final
class GetNut04QuoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quote_id", b"quote_id"]) -> None: ...

global___GetNut04QuoteRequest = GetNut04QuoteRequest

@typing.final
class GetNut04QuoteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_FIELD_NUMBER: builtins.int
    @property
    def quote(self) -> global___Nut04Quote: ...
    def __init__(
        self,
        *,
        quote: global___Nut04Quote | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["quote", b"quote"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["quote", b"quote"]) -> None: ...

global___GetNut04QuoteResponse = GetNut04QuoteResponse

@typing.final
class GetNut05QuoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quote_id", b"quote_id"]) -> None: ...

global___GetNut05QuoteRequest = GetNut05QuoteRequest

@typing.final
class GetNut05QuoteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_FIELD_NUMBER: builtins.int
    @property
    def quote(self) -> global___Nut05Quote: ...
    def __init__(
        self,
        *,
        quote: global___Nut05Quote | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["quote", b"quote"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["quote", b"quote"]) -> None: ...

global___GetNut05QuoteResponse = GetNut05QuoteResponse

@typing.final
class UpdateQuoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    state: builtins.str
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
        state: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quote_id", b"quote_id", "state", b"state"]) -> None: ...

global___UpdateQuoteRequest = UpdateQuoteRequest

@typing.final
class RotateNextKeysetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    MAX_ORDER_FIELD_NUMBER: builtins.int
    INPUT_FEE_PPK_FIELD_NUMBER: builtins.int
    unit: builtins.str
    max_order: builtins.int
    input_fee_ppk: builtins.int
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        max_order: builtins.int | None = ...,
        input_fee_ppk: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_input_fee_ppk", b"_input_fee_ppk", "_max_order", b"_max_order", "input_fee_ppk", b"input_fee_ppk", "max_order", b"max_order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_input_fee_ppk", b"_input_fee_ppk", "_max_order", b"_max_order", "input_fee_ppk", b"input_fee_ppk", "max_order", b"max_order", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_input_fee_ppk", b"_input_fee_ppk"]) -> typing.Literal["input_fee_ppk"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max_order", b"_max_order"]) -> typing.Literal["max_order"] | None: ...

global___RotateNextKeysetRequest = RotateNextKeysetRequest

@typing.final
class RotateNextKeysetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    MAX_ORDER_FIELD_NUMBER: builtins.int
    INPUT_FEE_PPK_FIELD_NUMBER: builtins.int
    id: builtins.str
    unit: builtins.str
    max_order: builtins.int
    input_fee_ppk: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        unit: builtins.str = ...,
        max_order: builtins.int = ...,
        input_fee_ppk: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "input_fee_ppk", b"input_fee_ppk", "max_order", b"max_order", "unit", b"unit"]) -> None: ...

global___RotateNextKeysetResponse = RotateNextKeysetResponse

@typing.final
class UpdateLightningFeeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEE_PERCENT_FIELD_NUMBER: builtins.int
    FEE_MIN_RESERVE_FIELD_NUMBER: builtins.int
    fee_percent: builtins.float
    fee_min_reserve: builtins.int
    def __init__(
        self,
        *,
        fee_percent: builtins.float | None = ...,
        fee_min_reserve: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_fee_min_reserve", b"_fee_min_reserve", "_fee_percent", b"_fee_percent", "fee_min_reserve", b"fee_min_reserve", "fee_percent", b"fee_percent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_fee_min_reserve", b"_fee_min_reserve", "_fee_percent", b"_fee_percent", "fee_min_reserve", b"fee_min_reserve", "fee_percent", b"fee_percent"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fee_min_reserve", b"_fee_min_reserve"]) -> typing.Literal["fee_min_reserve"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fee_percent", b"_fee_percent"]) -> typing.Literal["fee_percent"] | None: ...

global___UpdateLightningFeeRequest = UpdateLightningFeeRequest

@typing.final
class UpdateAuthLimitsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTH_RATE_LIMIT_PER_MINUTE_FIELD_NUMBER: builtins.int
    AUTH_MAX_BLIND_TOKENS_FIELD_NUMBER: builtins.int
    auth_rate_limit_per_minute: builtins.int
    auth_max_blind_tokens: builtins.int
    def __init__(
        self,
        *,
        auth_rate_limit_per_minute: builtins.int | None = ...,
        auth_max_blind_tokens: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_auth_max_blind_tokens", b"_auth_max_blind_tokens", "_auth_rate_limit_per_minute", b"_auth_rate_limit_per_minute", "auth_max_blind_tokens", b"auth_max_blind_tokens", "auth_rate_limit_per_minute", b"auth_rate_limit_per_minute"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_auth_max_blind_tokens", b"_auth_max_blind_tokens", "_auth_rate_limit_per_minute", b"_auth_rate_limit_per_minute", "auth_max_blind_tokens", b"auth_max_blind_tokens", "auth_rate_limit_per_minute", b"auth_rate_limit_per_minute"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_auth_max_blind_tokens", b"_auth_max_blind_tokens"]) -> typing.Literal["auth_max_blind_tokens"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_auth_rate_limit_per_minute", b"_auth_rate_limit_per_minute"]) -> typing.Literal["auth_rate_limit_per_minute"] | None: ...

global___UpdateAuthLimitsRequest = UpdateAuthLimitsRequest
