"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetInfoRequest = GetInfoRequest

@typing.final
class MintInfoContact(google.protobuf.message.Message):
    """Define the MintInfoContact message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    method: builtins.str
    """Define fields for MintInfoContact as needed"""
    info: builtins.str
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "method", b"method"]) -> None: ...

global___MintInfoContact = MintInfoContact

@typing.final
class GetInfoResponse(google.protobuf.message.Message):
    """Define the GetInfoResponse message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PUBKEY_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DESCRIPTION_LONG_FIELD_NUMBER: builtins.int
    CONTACT_FIELD_NUMBER: builtins.int
    MOTD_FIELD_NUMBER: builtins.int
    ICON_URL_FIELD_NUMBER: builtins.int
    URLS_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Optional field"""
    pubkey: builtins.str
    """Optional field"""
    version: builtins.str
    """Optional field"""
    description: builtins.str
    """Optional field"""
    description_long: builtins.str
    """Optional field"""
    motd: builtins.str
    """Optional field"""
    icon_url: builtins.str
    """Optional field"""
    time: builtins.int
    """Optional field (use int64 for larger integers)"""
    @property
    def contact(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MintInfoContact]:
        """Optional list of MintInfoContact"""

    @property
    def urls(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Optional list of strings"""

    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        pubkey: builtins.str | None = ...,
        version: builtins.str | None = ...,
        description: builtins.str | None = ...,
        description_long: builtins.str | None = ...,
        contact: collections.abc.Iterable[global___MintInfoContact] | None = ...,
        motd: builtins.str | None = ...,
        icon_url: builtins.str | None = ...,
        urls: collections.abc.Iterable[builtins.str] | None = ...,
        time: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_description_long", b"_description_long", "_icon_url", b"_icon_url", "_motd", b"_motd", "_name", b"_name", "_pubkey", b"_pubkey", "_time", b"_time", "_version", b"_version", "description", b"description", "description_long", b"description_long", "icon_url", b"icon_url", "motd", b"motd", "name", b"name", "pubkey", b"pubkey", "time", b"time", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_description_long", b"_description_long", "_icon_url", b"_icon_url", "_motd", b"_motd", "_name", b"_name", "_pubkey", b"_pubkey", "_time", b"_time", "_version", b"_version", "contact", b"contact", "description", b"description", "description_long", b"description_long", "icon_url", b"icon_url", "motd", b"motd", "name", b"name", "pubkey", b"pubkey", "time", b"time", "urls", b"urls", "version", b"version"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description_long", b"_description_long"]) -> typing.Literal["description_long"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_icon_url", b"_icon_url"]) -> typing.Literal["icon_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_motd", b"_motd"]) -> typing.Literal["motd"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pubkey", b"_pubkey"]) -> typing.Literal["pubkey"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_time", b"_time"]) -> typing.Literal["time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_version", b"_version"]) -> typing.Literal["version"] | None: ...

global___GetInfoResponse = GetInfoResponse

@typing.final
class UpdateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateResponse = UpdateResponse

@typing.final
class UpdateMotdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOTD_FIELD_NUMBER: builtins.int
    motd: builtins.str
    def __init__(
        self,
        *,
        motd: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["motd", b"motd"]) -> None: ...

global___UpdateMotdRequest = UpdateMotdRequest

@typing.final
class UpdateDescriptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    description: builtins.str
    def __init__(
        self,
        *,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description"]) -> None: ...

global___UpdateDescriptionRequest = UpdateDescriptionRequest

@typing.final
class UpdateIconUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ICON_URL_FIELD_NUMBER: builtins.int
    icon_url: builtins.str
    def __init__(
        self,
        *,
        icon_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["icon_url", b"icon_url"]) -> None: ...

global___UpdateIconUrlRequest = UpdateIconUrlRequest

@typing.final
class UpdateNameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___UpdateNameRequest = UpdateNameRequest

@typing.final
class UpdateUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["url", b"url"]) -> None: ...

global___UpdateUrlRequest = UpdateUrlRequest

@typing.final
class UpdateContactRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    method: builtins.str
    info: builtins.str
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "method", b"method"]) -> None: ...

global___UpdateContactRequest = UpdateContactRequest

@typing.final
class UpdateNut04Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    unit: builtins.str
    method: builtins.str
    disabled: builtins.bool
    min: builtins.int
    max: builtins.int
    description: builtins.bool
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        method: builtins.str = ...,
        disabled: builtins.bool | None = ...,
        min: builtins.int | None = ...,
        max: builtins.int | None = ...,
        description: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "description", b"description", "disabled", b"disabled", "max", b"max", "min", b"min"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "description", b"description", "disabled", b"disabled", "max", b"max", "method", b"method", "min", b"min", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_disabled", b"_disabled"]) -> typing.Literal["disabled"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max", b"_max"]) -> typing.Literal["max"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_min", b"_min"]) -> typing.Literal["min"] | None: ...

global___UpdateNut04Request = UpdateNut04Request

@typing.final
class UpdateNut05Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    unit: builtins.str
    method: builtins.str
    disabled: builtins.bool
    min: builtins.int
    max: builtins.int
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        method: builtins.str = ...,
        disabled: builtins.bool | None = ...,
        min: builtins.int | None = ...,
        max: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "disabled", b"disabled", "max", b"max", "min", b"min"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_disabled", b"_disabled", "_max", b"_max", "_min", b"_min", "disabled", b"disabled", "max", b"max", "method", b"method", "min", b"min", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_disabled", b"_disabled"]) -> typing.Literal["disabled"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max", b"_max"]) -> typing.Literal["max"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_min", b"_min"]) -> typing.Literal["min"] | None: ...

global___UpdateNut05Request = UpdateNut05Request

@typing.final
class UpdateQuoteTtlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MINT_TTL_FIELD_NUMBER: builtins.int
    MELT_TTL_FIELD_NUMBER: builtins.int
    mint_ttl: builtins.int
    melt_ttl: builtins.int
    def __init__(
        self,
        *,
        mint_ttl: builtins.int | None = ...,
        melt_ttl: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_melt_ttl", b"_melt_ttl", "_mint_ttl", b"_mint_ttl", "melt_ttl", b"melt_ttl", "mint_ttl", b"mint_ttl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_melt_ttl", b"_melt_ttl", "_mint_ttl", b"_mint_ttl", "melt_ttl", b"melt_ttl", "mint_ttl", b"mint_ttl"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_melt_ttl", b"_melt_ttl"]) -> typing.Literal["melt_ttl"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_mint_ttl", b"_mint_ttl"]) -> typing.Literal["mint_ttl"] | None: ...

global___UpdateQuoteTtlRequest = UpdateQuoteTtlRequest

@typing.final
class UpdateNut04QuoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTE_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    quote_id: builtins.str
    state: builtins.str
    def __init__(
        self,
        *,
        quote_id: builtins.str = ...,
        state: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quote_id", b"quote_id", "state", b"state"]) -> None: ...

global___UpdateNut04QuoteRequest = UpdateNut04QuoteRequest

@typing.final
class RotateNextKeysetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIT_FIELD_NUMBER: builtins.int
    MAX_ORDER_FIELD_NUMBER: builtins.int
    INPUT_FEE_PPK_FIELD_NUMBER: builtins.int
    unit: builtins.str
    max_order: builtins.int
    input_fee_ppk: builtins.int
    def __init__(
        self,
        *,
        unit: builtins.str = ...,
        max_order: builtins.int | None = ...,
        input_fee_ppk: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_input_fee_ppk", b"_input_fee_ppk", "_max_order", b"_max_order", "input_fee_ppk", b"input_fee_ppk", "max_order", b"max_order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_input_fee_ppk", b"_input_fee_ppk", "_max_order", b"_max_order", "input_fee_ppk", b"input_fee_ppk", "max_order", b"max_order", "unit", b"unit"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_input_fee_ppk", b"_input_fee_ppk"]) -> typing.Literal["input_fee_ppk"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max_order", b"_max_order"]) -> typing.Literal["max_order"] | None: ...

global___RotateNextKeysetRequest = RotateNextKeysetRequest

@typing.final
class RotateNextKeysetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    MAX_ORDER_FIELD_NUMBER: builtins.int
    INPUT_FEE_PPK_FIELD_NUMBER: builtins.int
    id: builtins.str
    unit: builtins.str
    max_order: builtins.int
    input_fee_ppk: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        unit: builtins.str = ...,
        max_order: builtins.int = ...,
        input_fee_ppk: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "input_fee_ppk", b"input_fee_ppk", "max_order", b"max_order", "unit", b"unit"]) -> None: ...

global___RotateNextKeysetResponse = RotateNextKeysetResponse
