# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cashu.mint.management_rpc.protos.management_pb2 as management__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MintStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/management.Mint/GetInfo',
                request_serializer=management__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=management__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.UpdateMotd = channel.unary_unary(
                '/management.Mint/UpdateMotd',
                request_serializer=management__pb2.UpdateMotdRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateShortDescription = channel.unary_unary(
                '/management.Mint/UpdateShortDescription',
                request_serializer=management__pb2.UpdateDescriptionRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateLongDescription = channel.unary_unary(
                '/management.Mint/UpdateLongDescription',
                request_serializer=management__pb2.UpdateDescriptionRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateIconUrl = channel.unary_unary(
                '/management.Mint/UpdateIconUrl',
                request_serializer=management__pb2.UpdateIconUrlRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateName = channel.unary_unary(
                '/management.Mint/UpdateName',
                request_serializer=management__pb2.UpdateNameRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.AddUrl = channel.unary_unary(
                '/management.Mint/AddUrl',
                request_serializer=management__pb2.UpdateUrlRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.RemoveUrl = channel.unary_unary(
                '/management.Mint/RemoveUrl',
                request_serializer=management__pb2.UpdateUrlRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.AddContact = channel.unary_unary(
                '/management.Mint/AddContact',
                request_serializer=management__pb2.UpdateContactRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.RemoveContact = channel.unary_unary(
                '/management.Mint/RemoveContact',
                request_serializer=management__pb2.UpdateContactRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateNut04 = channel.unary_unary(
                '/management.Mint/UpdateNut04',
                request_serializer=management__pb2.UpdateNut04Request.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateNut05 = channel.unary_unary(
                '/management.Mint/UpdateNut05',
                request_serializer=management__pb2.UpdateNut05Request.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateQuoteTtl = channel.unary_unary(
                '/management.Mint/UpdateQuoteTtl',
                request_serializer=management__pb2.UpdateQuoteTtlRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateNut04Quote = channel.unary_unary(
                '/management.Mint/UpdateNut04Quote',
                request_serializer=management__pb2.UpdateNut04QuoteRequest.SerializeToString,
                response_deserializer=management__pb2.UpdateNut04QuoteRequest.FromString,
                _registered_method=True)
        self.RotateNextKeyset = channel.unary_unary(
                '/management.Mint/RotateNextKeyset',
                request_serializer=management__pb2.RotateNextKeysetRequest.SerializeToString,
                response_deserializer=management__pb2.RotateNextKeysetResponse.FromString,
                _registered_method=True)


class MintServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMotd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShortDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLongDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIconUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNut04(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNut05(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuoteTtl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNut04Quote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateNextKeyset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MintServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=management__pb2.GetInfoRequest.FromString,
                    response_serializer=management__pb2.GetInfoResponse.SerializeToString,
            ),
            'UpdateMotd': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMotd,
                    request_deserializer=management__pb2.UpdateMotdRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateShortDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShortDescription,
                    request_deserializer=management__pb2.UpdateDescriptionRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateLongDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLongDescription,
                    request_deserializer=management__pb2.UpdateDescriptionRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateIconUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIconUrl,
                    request_deserializer=management__pb2.UpdateIconUrlRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateName': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateName,
                    request_deserializer=management__pb2.UpdateNameRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'AddUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUrl,
                    request_deserializer=management__pb2.UpdateUrlRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'RemoveUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUrl,
                    request_deserializer=management__pb2.UpdateUrlRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=management__pb2.UpdateContactRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'RemoveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContact,
                    request_deserializer=management__pb2.UpdateContactRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateNut04': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNut04,
                    request_deserializer=management__pb2.UpdateNut04Request.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateNut05': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNut05,
                    request_deserializer=management__pb2.UpdateNut05Request.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateQuoteTtl': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuoteTtl,
                    request_deserializer=management__pb2.UpdateQuoteTtlRequest.FromString,
                    response_serializer=management__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateNut04Quote': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNut04Quote,
                    request_deserializer=management__pb2.UpdateNut04QuoteRequest.FromString,
                    response_serializer=management__pb2.UpdateNut04QuoteRequest.SerializeToString,
            ),
            'RotateNextKeyset': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateNextKeyset,
                    request_deserializer=management__pb2.RotateNextKeysetRequest.FromString,
                    response_serializer=management__pb2.RotateNextKeysetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'management.Mint', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('management.Mint', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mint(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/GetInfo',
            management__pb2.GetInfoRequest.SerializeToString,
            management__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMotd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateMotd',
            management__pb2.UpdateMotdRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShortDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateShortDescription',
            management__pb2.UpdateDescriptionRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLongDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateLongDescription',
            management__pb2.UpdateDescriptionRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIconUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateIconUrl',
            management__pb2.UpdateIconUrlRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateName',
            management__pb2.UpdateNameRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/AddUrl',
            management__pb2.UpdateUrlRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/RemoveUrl',
            management__pb2.UpdateUrlRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/AddContact',
            management__pb2.UpdateContactRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/RemoveContact',
            management__pb2.UpdateContactRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNut04(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateNut04',
            management__pb2.UpdateNut04Request.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNut05(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateNut05',
            management__pb2.UpdateNut05Request.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQuoteTtl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateQuoteTtl',
            management__pb2.UpdateQuoteTtlRequest.SerializeToString,
            management__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNut04Quote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/UpdateNut04Quote',
            management__pb2.UpdateNut04QuoteRequest.SerializeToString,
            management__pb2.UpdateNut04QuoteRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateNextKeyset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.Mint/RotateNextKeyset',
            management__pb2.RotateNextKeysetRequest.SerializeToString,
            management__pb2.RotateNextKeysetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
