name: prepare

inputs:
  python-version:
    description: "Python Version"
    required: true
    default: "3.10"
  poetry-version:
    description: "Poetry Version"
    default: "2.3.2"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry ${{ inputs.poetry-version }}
      run: |
        python -m pip install --upgrade "poetry==${{ inputs.poetry-version }}"
      shell: bash
    - name: Install dependencies
      run: |
        poetry install
      shell: bash
