name: prepare

inputs:
  python-version:
    description: "Python Version"
    required: true
    default: "3.10"
  poetry-version:
    description: "Poetry Version"
    default: "1.8.5"

runs:
  using: "composite"
  steps:
    - name: Set up Poetry ${{ inputs.poetry-version }}
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ inputs.poetry-version }}
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
    - name: Install dependencies
      run: |
        poetry install
      shell: bash
