name: mutation mint

on:
  schedule:
    - cron: "0 1 * * 2"
  workflow_dispatch:

jobs:
  mutation:
    uses: ./.github/workflows/_mutation-profile.yml
    with:
      profile: mint
      target: "cashu.mint*"
      prefix: "cashu.mint"
