name: mutation lightning

on:
  schedule:
    - cron: "0 1 * * 4"
  workflow_dispatch:

jobs:
  mutation:
    uses: ./.github/workflows/_mutation-profile.yml
    with:
      profile: lightning
      shards: "[0,1]"
      prefix: "cashu.lightning"
