name: mutation wallet

on:
  schedule:
    - cron: "0 1 * * 3"
  workflow_dispatch:

jobs:
  mutation:
    uses: ./.github/workflows/_mutation-profile.yml
    with:
      profile: wallet
      target: "cashu.wallet*"
      prefix: "cashu.wallet"
