name: Pip package

on:
  push:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"]
          uv-version: ["0.11.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare
        with:
          python-version: ${{ matrix.python-version }}
          uv-version: ${{ matrix.uv-version }}

      - name: Verify Versions
        if: github.event_name == 'release'
        run: |
          python3 scripts/check_version.py "${{ github.event.release.tag_name }}"

      - name: Build package
        run: |
          uv build

      - name: Install package
        run: |
          uv pip install dist/*.whl

      - name: Upload to PyPI on release
        if: github.event_name == 'release' && github.event.action == 'released'
        run: |
          uv publish --token "${{ secrets.PYPI_API_TOKEN }}"
