name: regtest-setup

on:
  workflow_call:
    inputs:
      os-version:
        default: "ubuntu-latest"
        type: string
    outputs:
      regtest-service-url:
        description: "URL of the regtest service"
        value: ${{ jobs.setup-regtest.outputs.regtest-service-url }}

jobs:
  setup-regtest:
    runs-on: ${{ inputs.os-version }}
    timeout-minutes: 15
    outputs:
      regtest-service-url: ${{ steps.regtest-info.outputs.service-url }}

    services:
      regtest:
        image: ghcr.io/callebtc/cashu-regtest-environment:sha-e4a2558968828f130e8668c88334435f5a67987d
        ports:
          # Map all needed ports to make them accessible
          - 5001:5001  # LNbits
          - 8081:8081  # LND REST
          - 10009:10009  # LND RPC
          - 3001:3001  # CoreLightning REST
          - 3010:3010  # CLN REST
        options: >-
          --health-cmd "curl -f http://localhost:5001 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 20s
          --name regtest-environment
          --volume regtest-data:/regtest/data
          --volume /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v3

      - name: Wait for regtest environment
        run: |
          # Wait for the regtest environment to be fully up
          echo "Waiting for regtest environment to be ready..."
          timeout 300 bash -c 'until curl -s http://localhost:5001 > /dev/null; do sleep 5; echo "Waiting..."; done'
          echo "Regtest environment is ready"

      - name: Export regtest data to shared location
        run: |
          # Create a directory to store the regtest data
          mkdir -p /tmp/regtest-data
          docker cp regtest-environment:/regtest/data /tmp/regtest-data
          chmod -R 777 /tmp/regtest-data

      - name: Upload regtest data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: regtest-data
          path: /tmp/regtest-data/data
          retention-days: 1

      - name: Save regtest info
        id: regtest-info
        run: |
          echo "service-url=http://localhost" >> $GITHUB_OUTPUT
